# src/projectdavid/events.py
from dataclasses import asdict, dataclass
from typing import Any, Callable, Dict, Optional


@dataclass
class StreamEvent:
    """Base class for all stream events with built-in serialization."""

    run_id: str

    def to_dict(self) -> Dict[str, Any]:
        """Converts the dataclass to a dictionary and adds the 'type' discriminator."""
        data = asdict(self)
        # Identify the event type for the front-end
        data["type"] = self.get_event_type()
        return data

    def get_event_type(self) -> str:
        mapping = {
            "ContentEvent": "content",
            "ReasoningEvent": "reasoning",
            "DecisionEvent": "decision",
            "PlanEvent": "plan",
            "ToolCallRequestEvent": "tool_call_manifest",
            "WebStatusEvent": "web_status",
            "ResearchStatusEvent": "research_status",
            "ScratchpadEvent": "scratchpad_status",
            "HotCodeEvent": "hot_code",
            "CodeExecutionOutputEvent": "code_output",
            "ComputerExecutionOutputEvent": "computer_output",
            "CodeExecutionGeneratedFileEvent": "generated_file",
            "EngineerStatusEvent": "engineer_status",
            "ToolInterceptEvent": "tool_intercept",
            "CodeStatusEvent": "code_status",  # <-- Added missing registry entry
        }
        return mapping.get(self.__class__.__name__, "unknown")


@dataclass
class ScratchpadEvent(StreamEvent):
    """
    Represents a scratchpad operation (read/update/append).
    Corresponds to the ScratchpadStatus.js frontend component.
    """

    operation: str
    state: str
    activity: Optional[str] = None
    tool: Optional[str] = None
    entry: Optional[str] = None
    content: Optional[str] = None
    assistant_id: Optional[str] = None


@dataclass
class ResearchStatusEvent(StreamEvent):
    """Represents user-visible progress updates during tool execution."""

    activity: str
    tool: Optional[str] = None
    state: str = "in_progress"

    def __str__(self):
        return self.activity


@dataclass
class ContentEvent(StreamEvent):
    """Represents a text delta from the assistant."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class ReasoningEvent(StreamEvent):
    """Represents a 'thinking' delta (DeepSeek R1/V3)."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class DecisionEvent(StreamEvent):
    """Represents a structural decision payload (JSON) from the assistant."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class PlanEvent(StreamEvent):
    """Represents a strategic planning delta (Level 3) from the assistant."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class HotCodeEvent(StreamEvent):
    """Real-time code being typed by the model BEFORE execution."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class CodeExecutionOutputEvent(StreamEvent):
    """Stdout/Stderr output from the code sandbox."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class ComputerExecutionOutputEvent(StreamEvent):
    """Output from the shell/computer execution tool."""

    content: str

    def __str__(self):
        return self.content


@dataclass
class CodeExecutionGeneratedFileEvent(StreamEvent):
    """A file (plot, csv) generated by the code interpreter."""

    filename: str
    file_id: str
    mime_type: str
    url: Optional[str] = None
    base64_data: Optional[str] = None


@dataclass
class WebStatusEvent(StreamEvent):
    """Represents a lifecycle change (complete, failed, tool_output_received)."""

    status: str
    message: Optional[str] = None
    tool: Optional[str] = None


@dataclass
class EngineerStatusEvent(StreamEvent):
    """Represents a lifecycle update from the Network Engineer tools."""

    activity: str
    tool: Optional[str] = None
    state: str = "in_progress"

    def __str__(self):
        return self.activity


@dataclass
class ToolInterceptEvent(StreamEvent):
    tool_name: str
    args: Dict[str, Any]
    action_id: Optional[str] = None
    origin: Optional[str] = None
    thread_id: Optional[str] = None
    tool_call_id: Optional[str] = None
    origin_run_id: Optional[str] = None  # ← NEW: junior's ephemeral run_id
    origin_assistant_id: Optional[str] = None  # ← NEW: junior's ephemeral assistant_id

    def execute_intercepted(
        self,
        tool_executor: Callable[[str, Dict[str, Any]], str],
        runs_client: Any,
        actions_client: Any,
        messages_client: Any,
    ) -> bool:
        """
        Executes this intercepted worker tool call server-side.
        Mirrors ToolCallRequestEvent.execute() but scoped to the worker's
        thread and assistant, both carried on the event itself.
        """
        if not self.origin_assistant_id:
            raise ValueError(
                "ToolInterceptEvent is missing origin_assistant_id. "
                "Ensure the delegation handler populates it before yielding."
            )

        return runs_client.execute_delegated_action(
            tool_name=self.tool_name,
            args=self.args,
            action_id=self.action_id,
            thread_id=self.thread_id,
            assistant_id=self.origin_assistant_id,  # ← resolved from self, no external lookup
            tool_executor=tool_executor,
            actions_client=actions_client,
            messages_client=messages_client,
            tool_call_id=self.tool_call_id,
        )


@dataclass
class CodeStatusEvent(StreamEvent):
    """
    Represents a code interpreter lifecycle update.
    Emitted by CodeExecutionMixin as type='code_status'.
    Distinct from ResearchStatusEvent (deep research/orchestration)
    so the frontend can route them independently.
    """

    activity: str
    state: str
    tool: Optional[str] = None


class ToolCallRequestEvent(StreamEvent):
    """
    A fully accumulated tool call request.
    Level 3 Update: Added tool_call_id to ensure ID-Parity between the
    Assistant's plan and the Tool's response in the dialogue history.
    """

    def __init__(
        self,
        run_id: str,
        tool_name: str,
        args: Dict[str, Any],
        thread_id: str,
        assistant_id: str,
        _runs_client: Any,
        _actions_client: Any,
        _messages_client: Any,
        action_id: Optional[str] = None,
        tool_call_id: Optional[str] = None,
    ):
        super().__init__(run_id)
        self.tool_name = tool_name
        self.args = args
        self.action_id = action_id
        self.tool_call_id = tool_call_id
        self._thread_id = thread_id
        self._assistant_id = assistant_id
        self._runs_client = _runs_client
        self._actions_client = _actions_client
        self._messages_client = _messages_client

        self.executed = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "type": "tool_call_manifest",
            "run_id": self.run_id,
            "tool": self.tool_name,
            "args": self.args,
            "action_id": self.action_id,
            "tool_call_id": self.tool_call_id,
        }

    def execute(self, tool_executor: Callable[[str, Dict[str, Any]], str]) -> bool:
        """
        Helper to run local code and submit results.
        Level 3: Propagates tool_call_id to execute_pending_action to close the loop.
        """
        success = self._runs_client.execute_pending_action(
            run_id=self.run_id,
            thread_id=self._thread_id,
            assistant_id=self._assistant_id,
            tool_executor=tool_executor,
            actions_client=self._actions_client,
            messages_client=self._messages_client,
            streamed_args=self.args,
            action_id=self.action_id,
            tool_name=self.tool_name,
            tool_call_id=self.tool_call_id,
        )

        if success:
            self.executed = True

        return success
